package edubit;

import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.*;
import javax.swing.*;

public class Employees extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    private ImageIcon format = null;
    //strin filename
    String filename = null;
    byte[] person_image = null;

    private String gender;

    public Employees() {
        initComponents();
        conn = db.java_db();
        SchoolInfo();
        Update_table();
        loader.setVisible(false);
    }
    ResultSet rsUpda;

    private void Update_table() {

        try {
            String sql = "select EMPLOYEE_ID,FIRST_NAME,LAST_NAME,POSITION,BIRTH_DAY,MOBILE_NO,SEX,District,Sector FROM EMPLOYEE_INFO LIMIT 30";

            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            rsUpda = rs;
            empData.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "It is not connceted.");

        } finally {
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
        }

    }

    public void close() {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_tclear = new javax.swing.JButton();
        txt_birthday = new javax.swing.JTextField();
        txt_position = new javax.swing.JTextField();
        cmd_tdelete = new javax.swing.JButton();
        cmd_save = new javax.swing.JButton();
        txt_tupdate = new javax.swing.JButton();
        txt_lastname = new javax.swing.JTextField();
        txt_mobile = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_sex = new javax.swing.JTextField();
        txt_firstname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        empId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        empData = new javax.swing.JTable();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        lbl_img1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        dst = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        province = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        sect = new javax.swing.JComboBox<>();
        loader = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_emp = new javax.swing.JLabel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        lblimg = new javax.swing.JLabel();
        about = new javax.swing.JButton();
        schoolName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 102)));
        jPanel1.setForeground(new java.awt.Color(153, 153, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Last Name:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Mobile No:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("First Name:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Birth Day:");

        txt_tclear.setBackground(new java.awt.Color(255, 255, 255));
        txt_tclear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_tclear.setIcon(new javax.swing.ImageIcon("C:\\Users\\ThinkPad\\Documents\\NetBeansProjects\\RPEMS\\images\\erase-128.png")); // NOI18N
        txt_tclear.setText("Clear");
        txt_tclear.setToolTipText("Clear Data");
        txt_tclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tclearActionPerformed(evt);
            }
        });

        txt_birthday.setToolTipText("Enter BOD: yyyy-mm-dd");
        txt_birthday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_birthdayActionPerformed(evt);
            }
        });

        txt_position.setToolTipText("Enter Duty");

        cmd_tdelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmd_tdelete.setForeground(new java.awt.Color(255, 0, 0));
        cmd_tdelete.setIcon(new javax.swing.ImageIcon("C:\\Users\\ThinkPad\\Documents\\NetBeansProjects\\RPEMS\\images\\s_cancel.png")); // NOI18N
        cmd_tdelete.setText("Delete");
        cmd_tdelete.setToolTipText("Delete The Selected Data");
        cmd_tdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_tdeleteActionPerformed(evt);
            }
        });

        cmd_save.setBackground(new java.awt.Color(255, 255, 255));
        cmd_save.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmd_save.setForeground(new java.awt.Color(51, 0, 51));
        cmd_save.setIcon(new javax.swing.ImageIcon("C:\\Users\\ThinkPad\\Documents\\NetBeansProjects\\RPEMS\\images\\Save-icon.png")); // NOI18N
        cmd_save.setText("Save");
        cmd_save.setToolTipText("Save all the input data");
        cmd_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_saveActionPerformed(evt);
            }
        });

        txt_tupdate.setBackground(new java.awt.Color(255, 255, 255));
        txt_tupdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_tupdate.setIcon(new javax.swing.ImageIcon("C:\\Users\\ThinkPad\\Documents\\NetBeansProjects\\RPEMS\\images\\update icon.png")); // NOI18N
        txt_tupdate.setText("Update");
        txt_tupdate.setToolTipText("Update The Selected Data");
        txt_tupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tupdateActionPerformed(evt);
            }
        });

        txt_lastname.setToolTipText("Enter last name");

        txt_mobile.setToolTipText("Enter Your Mobile Number");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Sex:");

        txt_sex.setToolTipText("male,famale");

        txt_firstname.setToolTipText("Enter First Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Position:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Employee's Information System");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Employee ID");

        empId.setEditable(false);
        empId.setToolTipText("ID");
        empId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empIdMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                empIdMousePressed(evt);
            }
        });

        empData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        empData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empDataMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                empDataMouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(empData);

        jDesktopPane1.setLayer(lbl_img1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_img1, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_img1, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton4.setForeground(new java.awt.Color(0, 153, 153));
        jButton4.setText("Browse");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setText("YYYY-MM-DD");

        jLabel11.setText("07XXXXXXX");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("District");

        dst.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dst.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select District" }));
        dst.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                dstPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Province");

        province.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        province.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Province", "Kigali", "Southern", "Western", "Northern", "Eastern" }));
        province.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                provincePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Sector");

        sect.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Sector" }));
        sect.setToolTipText("");

        loader.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        loader.setIcon(new javax.swing.ImageIcon("C:\\Users\\ThinkPad\\Documents\\NetBeansProjects\\RPEMS\\images\\waitloader.gif")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dst, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sect, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(7, 7, 7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(province, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txt_mobile, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_firstname)
                            .addComponent(txt_lastname)
                            .addComponent(txt_position)
                            .addComponent(txt_birthday)
                            .addComponent(empId)
                            .addComponent(txt_sex, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(loader, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cmd_save, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_tupdate)
                                        .addComponent(txt_tclear, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cmd_tdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(180, 180, 180)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cmd_save)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_tupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_tclear)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmd_tdelete)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(loader, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel5)
                                            .addComponent(empId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(txt_firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txt_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel4)
                                            .addComponent(txt_position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel6)
                                            .addComponent(txt_birthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7)
                                            .addComponent(txt_mobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel12)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel14)
                                                .addGap(2, 2, 2))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel8)
                                                    .addComponent(txt_sex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(province, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(dst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(sect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(187, 187, 187)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(55, 60, 68));
        jPanel2.setForeground(java.awt.Color.darkGray);
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 182, 320, 0));

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\ThinkPad\\Documents\\NetBeansProjects\\RPEMS\\images\\Copy of cover_photo.png")); // NOI18N
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 370, 150));

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\ThinkPad\\Documents\\NetBeansProjects\\RPEMS\\images\\rptech.png")); // NOI18N
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 270, 160));
        jPanel2.add(txt_emp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jDesktopPane2.setLayer(lblimg, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblimg, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblimg, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jDesktopPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, 180, 140));

        about.setBackground(new java.awt.Color(204, 204, 0));
        about.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        about.setIcon(new javax.swing.ImageIcon("C:\\Users\\ThinkPad\\Documents\\NetBeansProjects\\RPEMS\\images\\closer.png")); // NOI18N
        about.setText("Close");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        jPanel2.add(about, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 180, -1, 30));

        schoolName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        schoolName.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(schoolName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1017, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_tclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tclearActionPerformed

        ClearFields();

    }//GEN-LAST:event_txt_tclearActionPerformed

    private void txt_birthdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_birthdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_birthdayActionPerformed

    private void cmd_tdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_tdeleteActionPerformed

        int p = JOptionPane.showConfirmDialog(null, "Are you Sure to Delete?", "Delete", JOptionPane.YES_NO_OPTION);
        if (p == 0) {
            String sql = "delete from employee_info where Employee_id=?";
            try {
                pst = conn.prepareStatement(sql);

                pst.setString(1, empId.getText());

                pst.execute();

                JOptionPane.showMessageDialog(null, "Data Deleted Successfully.");
                Update_table();
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(null, "We face a Problem.");
            }

        }
    }//GEN-LAST:event_cmd_tdeleteActionPerformed

    private void cmd_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_saveActionPerformed
        // TODO add your handling code here:
        String value1 = empId.getText();
        String value2 = txt_firstname.getText();
        String value3 = txt_lastname.getText();
        String value4 = txt_position.getText();
        String value6 = txt_birthday.getText();
        String value7 = txt_mobile.getText();

        String value8 = txt_sex.getText();
        String value9 = (String) dst.getSelectedItem();
        String value10 = (String) sect.getSelectedItem();

        if (value2.isEmpty() || value3.isEmpty() || value4.isEmpty() || value6.isEmpty() || value7.isEmpty() || value8.isEmpty() || value9.startsWith("Select") || value10.startsWith("Select") || person_image == null) {
            JOptionPane.showMessageDialog(null, "Fill All fields and browse picture", "BR Software Resolution", JOptionPane.WARNING_MESSAGE);
        } else if (value7.contains("ABCDEFGHIJKLMNOPQRSTUVWXYZqwertyuiopasdfghjklzxcvbnm") || !value7.startsWith("07")) {
            JOptionPane.showMessageDialog(null, "Unsupported phone Contact format");
        } else if (value7.length() != 10) {
            JOptionPane.showMessageDialog(null, "Too short Telephone Length");

        } else {
            int p = JOptionPane.showConfirmDialog(null, "Are you Sure to Save?", "Save", JOptionPane.YES_NO_OPTION);
            if (p == 0) {
                SwingWorker<Void, String> mySwingWorker;
                mySwingWorker = new SwingWorker<Void, String>() {
                    @Override
                    public Void doInBackground() throws InterruptedException {
                        saveEmployee();
                        Thread.sleep(500);
                        return null;
                    }
                };
                JButton btns[] = {txt_tupdate, txt_tclear, cmd_tdelete};
                String waitMsg = "Please Wait...";
                PleaseWait x = new PleaseWait();
                x.geekExecute(evt, mySwingWorker, loader, waitMsg, btns);
            }

        }
    }//GEN-LAST:event_cmd_saveActionPerformed
    String sqr2;
    private void txt_tupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tupdateActionPerformed

        int p = JOptionPane.showConfirmDialog(null, "Are you Sure to Update?", "Update", JOptionPane.YES_NO_OPTION);
        if (p == 0) {
            SwingWorker<Void, String> mySwingWorker;
            mySwingWorker = new SwingWorker<Void, String>() {
                @Override
                public Void doInBackground() throws InterruptedException {
                    updateEmp();
                    Thread.sleep(500);
                    return null;
                }
            };
            JButton btns[] = {txt_tupdate, txt_tclear, cmd_tdelete,cmd_save};
            String waitMsg = "Please Wait...";
            PleaseWait x = new PleaseWait();
            x.geekExecute(evt, mySwingWorker, loader, waitMsg, btns);

        }


    }//GEN-LAST:event_txt_tupdateActionPerformed

    private void empDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empDataMouseClicked

        int[] StudentRow = empData.getSelectedRows();
        int row = StudentRow[0];
        Object identity = empData.getValueAt(row, 0);
        String id = String.valueOf(identity);
        int value = Integer.parseInt(id);
        Search(value);
        cmd_save.setEnabled(false);

    }//GEN-LAST:event_empDataMouseClicked

    private void empDataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empDataMouseExited
        // cmd_save.setVisible(false);
    }//GEN-LAST:event_empDataMouseExited

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked

    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();

        filename = f.getAbsolutePath();
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(lbl_img1.getWidth(), lbl_img1.getHeight(), Image.SCALE_DEFAULT));
        lbl_img1.setIcon(imageIcon);
        try {

            File image = new File(filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];

            for (int readNum; (readNum = fis.read(buf)) != -1;) {

                bos.write(buf, 0, readNum);
            }
            person_image = bos.toByteArray();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void dstPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_dstPopupMenuWillBecomeInvisible

        if (dst.getSelectedItem().equals("Gasabo")) {
            sect.removeAllItems();
            sect.addItem("Select Sector");
            String kgl[] = {"Bumbogo", "Gatsata", "Jali", "Gikomero", "Gisozi", "Jabana", "Kinyinya", "Ndera", "Nduba", "Rusororo", "Rutunga", "Kacyiru", "Kimihurura", "Kimironko", "Remera"};
            for (int i = 0; i <= kgl.length - 1; i++) {
                sect.addItem(kgl[i]);
            }
        } else if (dst.getSelectedItem().equals("Kicukiro")) {
            sect.removeAllItems();
            sect.addItem("Select Sector");
            String kgl[] = {"Gahanga", "Gatenga", "Gikondo", "Kagarama", "Kanombe", "Kicukiro", "Kigarama", "Masaka", "Niboye", "Nyarugunga"};
            for (int i = 0; i <= kgl.length - 1; i++) {
                sect.addItem(kgl[i]);
            }
        } else if (dst.getSelectedItem().equals("Nyarugenge")) {
            sect.removeAllItems();
            sect.addItem("Select Sector");
            String kgl[] = {"Gitega", "Kanyinya", "Kigali", "Kimisagara", "Mageragere", "Muhima", "Nyakabanda", "Nyamirambo", "Nyarugenge", "Rwezamenyo"};
            for (int i = 0; i <= kgl.length - 1; i++) {
                sect.addItem(kgl[i]);
            }
        } else if (dst.getSelectedItem().equals("Gisagara")) {
            sect.removeAllItems();
            sect.addItem("Select Sector");
            String kgl[] = {"Gikonko", "Gishubi", "Kansi", "Kibilizi", "Kigembe", "Mamba", "Muganza", "Mugombwa", "Mukindo", "Musha", "Ndora", "Nyanza", "Save"};
            for (int i = 0; i <= kgl.length - 1; i++) {
                sect.addItem(kgl[i]);
            }
        } else if (dst.getSelectedItem().equals("Huye")) {
            sect.removeAllItems();
            sect.addItem("Select Sector");
            String kgl[] = {"Gishamvu", "Karama", "Kigoma", "Kinazi", "Maraba", "Mbazi", "Mukura", "Ngoma", "Ruhashya", "Huye", "Rusatira", "Rwaniro", "Simbi", "Tumba"};
            for (int i = 0; i <= kgl.length - 1; i++) {
                sect.addItem(kgl[i]);
            }
        } else if (dst.getSelectedItem().equals("Kamonyi")) {
            sect.removeAllItems();
            sect.addItem("Select Sector");
            String kgl[] = {"Gacurabwenge", "Karama", "Kayenzi", "Kayumbu", "Mugina", "Musambira", "Ngamba", "Nyamiyaga", "Nyarubaka", "Rugalika", "Rukoma", "Runda"};
            for (int i = 0; i <= kgl.length - 1; i++) {
                sect.addItem(kgl[i]);
            }
        } else if (dst.getSelectedItem().equals("Muhanga")) {
            sect.removeAllItems();
            sect.addItem("Select Sector");
            String kgl[] = {"Muhanga", "Cyeza", "Kibangu", "Kiyumba", "Mushishiro", "Kabacuzi", "Nyabinoni", "Nyamabuye", "Nyarusange", "Rongi", "Rugendabari", "Shyogwe"};
            for (int i = 0; i <= kgl.length - 1; i++) {
                sect.addItem(kgl[i]);
            }
        } else if (dst.getSelectedItem().equals("Nyamagabe")) {
            sect.removeAllItems();
            sect.addItem("Select Sector");
            String kgl[] = {"Buruhukiro", "Cyanika", "Gatare", "Kaduha", "Kamegeli", "Kibirizi", "Kibumbwe", "Kitabi", "Mbazi", "Mugano", "Musange", "Musebeya", "Mushubi", "Nkomane", "Gasaka", "Tare", "Uwinkingi"};
            for (int i = 0; i <= kgl.length - 1; i++) {
                sect.addItem(kgl[i]);
            }
        } else if (dst.getSelectedItem().equals("Nyanza")) {
            sect.removeAllItems();
            sect.addItem("Select Sector");
            String kgl[] = {"Busasamana", "Busoro", "Cyabakamyi", "Kibirizi", "Kigoma", "Mukingo", "Muyira", "Ntyazo", "Nyagisozi", "Rwabicuma"};
            for (int i = 0; i <= kgl.length - 1; i++) {
                sect.addItem(kgl[i]);
            }
        } else if (dst.getSelectedItem().equals("Ruhango")) {
            sect.removeAllItems();
            sect.addItem("Select Sector");
            String kgl[] = {"Kinazi", "Byimana", "Bweramana", "Mbuye", "Ruhango", "Mwendo", "Kinihira", "Ntongwe", "Kabagari"};
            for (int i = 0; i <= kgl.length - 1; i++) {
                sect.addItem(kgl[i]);
            }
        } else if (dst.getSelectedItem().equals("Nyaruguru")) {
            sect.removeAllItems();
            sect.addItem("Select Sector");
            String kgl[] = {"Cyahinda", "Busanze", "Kibeho", "Mata", "Munini", "Kivu", "Ngera", "Ngoma", "Nyabimata", "Nyagisozi", "Muganza", "Ruheru", "Ruramba", "Rusenge"};
            for (int i = 0; i <= kgl.length - 1; i++) {
                sect.addItem(kgl[i]);
            }
        } else if (dst.getSelectedItem().equals("Karongi")) {
            sect.removeAllItems();
            sect.addItem("Select Sector");
            String kgl[] = {"Bwishyura", "Gishyita", "Gishari", "Gitesi", "Mubuga", "Murambi", "Murundi", "Mutuntu", "Rubengera", "Rugabano", "Ruganda", "Rwankuba", "Twumba"};
            for (int i = 0; i <= kgl.length - 1; i++) {
                sect.addItem(kgl[i]);
            }
        } else if (dst.getSelectedItem().equals("Nyabihu")) {
            sect.removeAllItems();
            sect.addItem("Select Sector");
            String kgl[] = {"Bigogwe", "Jenda", "Jomba", "Kabatwa", "Karago", "Kintobo", "Mukamira", "Muringa", "Rambura", "Rugera", "Rurembo", "Shyira"};
            for (int i = 0; i <= kgl.length - 1; i++) {
                sect.addItem(kgl[i]);
            }
        } else if (dst.getSelectedItem().equals("Nyamasheke")) {
            sect.removeAllItems();
            sect.addItem("Select Sector");
            String kgl[] = {"Ruharambuga", "Bushekeri", "Bushenge", "Cyato", "Gihombo", "Kagano", "Kanjongo", "Karambi", "Karengera", "Kirimbi", "Macuba", "Nyabitekeri", "Mahembe", "Rangiro", "Shangi"};
            for (int i = 0; i <= kgl.length - 1; i++) {
                sect.addItem(kgl[i]);
            }
        } else if (dst.getSelectedItem().equals("Rusizi")) {
            sect.removeAllItems();
            sect.addItem("Select Sector");
            String kgl[] = {"Bugarama", "Butare", "Bweyeye", "Gikundamvura", "Gashonga", "Giheke", "Gihundwe", "Gitambi", "Kamembe", "Muganza", "Mururu", "Nkanka", "Nkombo", "Nkungu", "Nyakabuye", "Nyakarenzo", "Nzahaha", "Rwimbogo"};
            for (int i = 0; i <= kgl.length - 1; i++) {
                sect.addItem(kgl[i]);
            }
        } else if (dst.getSelectedItem().equals("Rubavu")) {
            sect.removeAllItems();
            sect.addItem("Select Sector");
            String kgl[] = {"Bugeshi", "Busasamana", "Cyanzarwe", "Gisenyi", "Kanama", "Nyakiliba", "Nyamyumba", "Nyundo", "Rubavu", "Rugerero"};
            for (int i = 0; i <= kgl.length - 1; i++) {
                sect.addItem(kgl[i]);
            }
        } else if (dst.getSelectedItem().equals("Rutsiro")) {
            sect.removeAllItems();
            sect.addItem("Select Sector");
            String kgl[] = {"Boneza", "Gihango", "Kigeyo", "Kivumu", "Munihira", "Mukura", "Murunda", "Musasa", "Mushonyi", "Mushubati", "Nyabirasi", "Ruhango", "Rusebeya"};
            for (int i = 0; i <= kgl.length - 1; i++) {
                sect.addItem(kgl[i]);
            }
        } else if (dst.getSelectedItem().equals("Nyagatare")) {
            sect.removeAllItems();
            sect.addItem("Select Sector");
            String kgl[] = {"Rwimiyaga", "Karangazi", "Nyagatare", "Katabagemu", "Rukomo", "Tabagwe", "Musheli", "Gatunda", "Mimuli", "Karama", "Matimba", "Mukama", "Rwempasha", "Kiyombe"};
            for (int i = 0; i <= kgl.length - 1; i++) {
                sect.addItem(kgl[i]);
            }
        } else if (dst.getSelectedItem().equals("Gatsibo")) {
            sect.removeAllItems();
            sect.addItem("Select Sector");
            String kgl[] = {"Gasange", "Gatsibo", "Gitoki", "Kabarore", "Kageyo", "Kiramuruzi", "Kiziguro", "Muhura", "Murambi", "Ngarama", "Nyagihanga", "Remera", "Rugarama", "Rwimbogo"};
            for (int i = 0; i <= kgl.length - 1; i++) {
                sect.addItem(kgl[i]);
            }
        } else if (dst.getSelectedItem().equals("Bugesera")) {
            sect.removeAllItems();
            sect.addItem("Select Sector");
            String kgl[] = {"Gashora", "Juru", "Kamabuye", "Ntarama", "Mareba", "Mayange", "Musenyi", "Mwogo", "Ngeruka", "Nyamata", "Nyarugenge", "Rilima", "Ruhuha", "Rweru", "Shyara"};
            for (int i = 0; i <= kgl.length - 1; i++) {
                sect.addItem(kgl[i]);
            }
        } else if (dst.getSelectedItem().equals("Kayonza")) {
            sect.removeAllItems();
            sect.addItem("Select Sector");
            String kgl[] = {"Gahini", "Kabare", "Kabarondo", "Mukarange", "Murama", "Murundi", "Mwiri", "Ndego", "Nyamirama", "Rukara", "Ruramira", "Rwinkwavu"};
            for (int i = 0; i <= kgl.length - 1; i++) {
                sect.addItem(kgl[i]);
            }
        } else if (dst.getSelectedItem().equals("Ngoma")) {
            sect.removeAllItems();
            sect.addItem("Select Sector");
            String kgl[] = {"Gashanda", "Jarama", "Karembo", "Kazo", "Kibungo", "Mugesera", "Murama", "Mutenderi", "Remera", "Rukira", "Rukumberi", "Rurenge", "Sake", "Zaza"};
            for (int i = 0; i <= kgl.length - 1; i++) {
                sect.addItem(kgl[i]);
            }
        } else if (dst.getSelectedItem().equals("Kirehe")) {
            sect.removeAllItems();
            sect.addItem("Select Sector");
            String kgl[] = {"Gahara", "Gatore", "Kigarama", "Kigina", "Kirehe", "Mahama", "Mpanga", "Musaza", "Mushikiri", "Nasho", "Nyamugari", "Nyarubuye"};
            for (int i = 0; i <= kgl.length - 1; i++) {
                sect.addItem(kgl[i]);
            }
        } else if (dst.getSelectedItem().equals("Rwamagana")) {
            sect.removeAllItems();
            sect.addItem("Select Sector");
            String kgl[] = {"Fumbwe", "Gahengeri", "Gishari", "Karenge", "Kigabiro", "Muhazi", "Munyaga", "Munyiginya", "Musha", "Muyumbu", "Mwulire", "Nyakariro", "Nzige", "Rubona"};
            for (int i = 0; i <= kgl.length - 1; i++) {
                sect.addItem(kgl[i]);
            }
        } else if (dst.getSelectedItem().equals("Burera")) {
            sect.removeAllItems();
            sect.addItem("Select Sector");
            String kgl[] = {"Bungwe", "Butaro", "Cyanika", "Cyeru", "Gahunga", "Gatebe", "Gitovu", "Kagogo", "Kinoni", "Kinyababa", "Kivuye", "Nemba", "Rugarama", "Rugendabari", "Ruhunde", "Rusarabuge", "Rwerere"};
            for (int i = 0; i <= kgl.length - 1; i++) {
                sect.addItem(kgl[i]);
            }
        } else if (dst.getSelectedItem().equals("Gakenke")) {
            sect.removeAllItems();
            sect.addItem("Select Sector");
            String kgl[] = {"Busengo", "Coko", "Cyabingo", "Gakenke", "Gashenyi", "Mugunga", "Janja", "Kamubuga", "Karambo", "Kivuruga", "Mataba", "Minazi", "Muhondo", "Muyongwe", "Muzo", "Nemba", "Ruli", "Rusasa", "Rushashi"};
            for (int i = 0; i <= kgl.length - 1; i++) {
                sect.addItem(kgl[i]);
            }
        } else if (dst.getSelectedItem().equals("Gicumbi")) {
            sect.removeAllItems();
            sect.addItem("Select Sector");
            String kgl[] = {"Bukure", "Bwisige", "Byumba", "Cyumba", "Giti", "Kaniga", "Manyagiro", "Miyove", "Kageyo", "Mukarange", "Muko", "Mutete", "Nyamiyaga", "Nyankenke II", "Rubaya", "Rukomo", "Rushaki", "Rutare", "Ruvune", "Rwamiko", "Shangasha"};
            for (int i = 0; i <= kgl.length - 1; i++) {
                sect.addItem(kgl[i]);
            }
        } else if (dst.getSelectedItem().equals("Musanze")) {
            sect.removeAllItems();
            sect.addItem("Select Sector");
            String kgl[] = {"Busogo", "Cyuve", "Gacaca", "Gashaki", "Gataraga", "Kimonyi", "Kinigi", "Muhoza", "Muko", "Musanze", "Nkotsi", "Nyange", "Remera", "Rwaza", "Shingiro"};
            for (int i = 0; i <= kgl.length - 1; i++) {
                sect.addItem(kgl[i]);
            }
        } else if (dst.getSelectedItem().equals("Rulindo")) {
            sect.removeAllItems();
            sect.addItem("Select Sector");
            String kgl[] = {"Base", "Burega", "Bushoki", "Buyoga", "Cyinzuzi", "Cyungo", "Kinihira", "Kisaro", "Masoro", "Mbogo", "Murambi", "Ngoma", "Ntarabana", "Rukozo", "Rusiga", "Shyorongi", "Tumba"};
            for (int i = 0; i <= kgl.length - 1; i++) {
                sect.addItem(kgl[i]);
            }
        } else if (dst.getSelectedItem().equals("Select District")) {
            sect.removeAllItems();
            sect.addItem("Select Sector");
        }
    }//GEN-LAST:event_dstPopupMenuWillBecomeInvisible

    private void provincePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_provincePopupMenuWillBecomeInvisible

        String prvnc = (String) province.getSelectedItem();
        if (prvnc.equals("Kigali")) {
            dst.removeAllItems();
            dst.addItem("Select District");
            dst.addItem("Gasabo");
            dst.addItem("Kicukiro");
            dst.addItem("Nyarugenge");
        } else if (prvnc.equals("Southern")) {
            dst.removeAllItems();
            dst.addItem("Select District");
            String southern[] = {"Gisagara", "Huye", "Kamonyi", "Muhanga", "Nyamagabe", "Nyanza", "Nyaruguru", "Ruhango"};
            for (int i = 0; i <= southern.length - 1; i++) {
                dst.addItem(southern[i]);
            }

        } else if (prvnc.equals("Western")) {
            dst.removeAllItems();
            dst.addItem("Select District");
            String western[] = {"Karongi", "Ngororero", "Nyabihu", "Nyamasheke", "Rubavu", "Rusizi", "Rutsiro"};
            for (int i = 0; i <= western.length - 1; i++) {
                dst.addItem(western[i]);
            }
        } else if (prvnc.equals("Northern")) {
            dst.removeAllItems();
            dst.addItem("Select District");
            String northen[] = {"Burera", "Gakenke", "Gicumbi", "Rulindo", "Musanze"};
            for (int i = 0; i <= northen.length - 1; i++) {
                dst.addItem(northen[i]);
            }
        } else if (prvnc.equals("Eastern")) {
            dst.removeAllItems();
            dst.addItem("Select District");
            String east[] = {"Nyagatare", "Gatsibo", "Kayonza", "Bugesera", "Kirehe", "Ngoma", "Rwamagana"};
            for (int i = 0; i <= east.length - 1; i++) {
                dst.addItem(east[i]);
            }
        } else if (prvnc.equals("Select Province")) {
            dst.removeAllItems();
            dst.addItem("Select District");
        }
    }//GEN-LAST:event_provincePopupMenuWillBecomeInvisible

    private void empIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empIdMouseClicked
        JOptionPane.showMessageDialog(null, "ID IS AUTO-GENERATED", "BR Warning", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_empIdMouseClicked

    private void empIdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empIdMousePressed
        JOptionPane.showMessageDialog(null, "ID IS AUTO-GENERATED", "BR Warning", JOptionPane.WARNING_MESSAGE);

    }//GEN-LAST:event_empIdMousePressed

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        this.dispose();
    }//GEN-LAST:event_aboutActionPerformed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        //        // TODO add your handling code here:
        //        int x = evt.getXOnScreen();
        //        int y = evt.getYOnScreen();
        //        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        //        // TODO add your handling code here:
        //        xx = evt.getX();
        //        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employees().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton about;
    private javax.swing.JButton cmd_save;
    private javax.swing.JButton cmd_tdelete;
    private javax.swing.JComboBox<String> dst;
    private javax.swing.JTable empData;
    private javax.swing.JTextField empId;
    private javax.swing.JButton jButton4;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lbl_img1;
    private javax.swing.JLabel lblimg;
    private javax.swing.JLabel loader;
    private javax.swing.JComboBox<String> province;
    private javax.swing.JLabel schoolName;
    private javax.swing.JComboBox<String> sect;
    private javax.swing.JTextField txt_birthday;
    private javax.swing.JLabel txt_emp;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_lastname;
    private javax.swing.JTextField txt_mobile;
    private javax.swing.JTextField txt_position;
    private javax.swing.JTextField txt_sex;
    private javax.swing.JButton txt_tclear;
    private javax.swing.JButton txt_tupdate;
    // End of variables declaration//GEN-END:variables

    private void Search(int id) {

        String sql = "select * from EMPLOYEE_INFO where EMPLOYEE_ID=?";
        try {
            pst = conn.prepareStatement(sql);
            pst.setInt(1, id);
            rs = pst.executeQuery();
            if (rs.next()) {
                int add1 = rs.getInt("EMPLOYEE_ID");
                empId.setText(String.valueOf(add1));

                String add2 = rs.getString("FIRST_NAME");
                txt_firstname.setText(add2);

                String add3 = rs.getString("LAST_NAME");
                txt_lastname.setText(add3);

                String add4 = rs.getString("POSITION");
                txt_position.setText(add4);

                String add5 = rs.getString("BIRTH_DAY");
                txt_birthday.setText(add5);

                String add6 = rs.getString("MOBILE_NO");
                txt_mobile.setText(add6);

                String add7 = rs.getString("SEX");
                txt_sex.setText(add7);

                String add8 = rs.getString("District");
                dst.removeAllItems();
                dst.addItem(add8);

                String add9 = rs.getString("Sector");
                sect.removeAllItems();
                sect.addItem(add9);
                Blob filenameBlob = rs.getBlob("Picture");
                byte[] content = filenameBlob.getBytes(1L, (int) filenameBlob.length());
                ImageIcon ik = new ImageIcon(content);
                Image img = ik.getImage();
                //ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(lbl_img.getWidth(), lbl_img.getHeight(), Image.SCALE_DEFAULT));
                Image newimg = img.getScaledInstance(lbl_img1.getWidth(), lbl_img1.getHeight(), Image.SCALE_DEFAULT);
                ik = new ImageIcon(newimg);
                lbl_img1.setIcon(ik);

            }

            //byte[] img = rs.getBytes("Image");
            //imageIcon imageIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(lbl_img.getWidth(), lbl_img.getHeight(), Image.SCALE_SMOOTH));
            //lbl_img.setIcon(imageIcon);
        } catch (SQLException e) {
            System.out.print("Caught : " + e);
        }
    }

    private void ClearFields() {
        empId.setText("");
        txt_firstname.setText("");
        txt_lastname.setText("");
        txt_position.setText("");
        txt_birthday.setText("");
        txt_mobile.setText("");
        txt_sex.setText("");
        province.setSelectedIndex(0);
        dst.removeAllItems();
        dst.addItem("Select District");
        sect.removeAllItems();
        sect.addItem("Select Sector");
        lbl_img1.setIcon(null);
        cmd_save.setEnabled(true);

    }

    private void SchoolInfo() {
        try {
            pst = conn.prepareStatement("SELECT * FROM SCHOOL_INFO");
            rs = pst.executeQuery();
            if (rs.next()) {
                schoolName.setText(rs.getString("SchoolName"));
                Blob filenameBlob = rs.getBlob("Logo");
                byte[] content = filenameBlob.getBytes(1L, (int) filenameBlob.length());
                ImageIcon ik = new ImageIcon(content);
                Image img = ik.getImage();
                //ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(lbl_img.getWidth(), lbl_img.getHeight(), Image.SCALE_DEFAULT));
                Image newimg = img.getScaledInstance(lblimg.getWidth(), lblimg.getHeight(), Image.SCALE_DEFAULT);
                ik = new ImageIcon(newimg);
                lblimg.setIcon(ik);
            }
        } catch (SQLException e) {
        }

    }

    private void saveEmployee() {
        try {
            String value9 = (String) dst.getSelectedItem();
            String value10 = (String) sect.getSelectedItem();
            String sql = "insert into employee_info (First_name,Last_name,Position,Picture,Birth_day,Mobile_no,Sex,District,Sector) values(?,?,?,?,?,?,?,?,?)";

            pst = conn.prepareStatement(sql);

            pst.setString(1, txt_firstname.getText());
            pst.setString(2, txt_lastname.getText());
            pst.setString(3, txt_position.getText());
            pst.setBytes(4, person_image);
            pst.setString(5, txt_birthday.getText());
            pst.setString(6, txt_mobile.getText());
            pst.setString(7, txt_sex.getText());
            pst.setString(8, value9);
            pst.setString(9, value10);

            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Saved Successfully.");
            Update_table();

        } catch (HeadlessException | SQLException e) {

            JOptionPane.showMessageDialog(null, "We face a Problem." + e);
        }
    }

    private void updateEmp() {
        try {

            String value1 = empId.getText();
            int store = Integer.parseInt(value1);
            String value2 = txt_firstname.getText();
            String value3 = txt_lastname.getText();
            String value4 = txt_position.getText();
            String value6 = txt_birthday.getText();
            String value7 = txt_mobile.getText();
            String value8 = txt_sex.getText();
            String value9 = (String) dst.getSelectedItem();
            String value10 = (String) sect.getSelectedItem();
            if (value2.isEmpty() || value3.isEmpty() || value4.isEmpty() || value6.isEmpty() || value7.isEmpty() || value8.isEmpty() || value9.isEmpty() || value10.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Fill All fields and browse picture");
            } else if (value7.length() != 10) {
                JOptionPane.showMessageDialog(null, "Too short Telephone Length");

            } else if (person_image != null) {
                byte[] x = person_image;
                sqr2 = "Update employee_info set First_name='" + value2 + "',Last_name='" + value3 + "',Position='" + value4 + "',Picture='" + person_image + "' ,Birth_day='" + value6 + "',Mobile_no='" + value7 + "',Sex='" + value8 + "',District='" + value9 + "',Sector='" + value10 + "' where Employee_id=?";

            } else if (person_image == null) {
                sqr2 = "Update employee_info set First_name='" + value2 + "',Last_name='" + value3 + "',Position='" + value4 + "',Birth_day='" + value6 + "',Mobile_no='" + value7 + "',Sex='" + value8 + "',District='" + value9 + "',Sector='" + value10 + "' where Employee_id=?";

            }

            pst = conn.prepareStatement(sqr2);
            pst.setInt(1, store);
            int upt = pst.executeUpdate();
            if (upt > 0) {
                JOptionPane.showMessageDialog(null, "Table Updated Successfully.");
                ClearFields();
                Update_table();
            }

        } catch (HeadlessException | SQLException e) {

            JOptionPane.showMessageDialog(null, "We face a Problem!\n\nBR Possible Support Solution\n-------------------------------\n\n"
                    + "1.Date of birth must be respected(yyyy-mm-dd) \n2." + e, "BR", 0);
        }

    }
}
