/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edubit;

import edubit.*;
import java.awt.Image;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author ThinkPad
 */
public final class LUnits extends javax.swing.JFrame {

    Connection conn = db.java_db();
    ;
    ResultSet rs = null;
    PreparedStatement pst = null;
    int result;

    /**
     * Creates new form Home_Data
     */
    /**
     * Creates new form Sectors
     */
    public LUnits() {
        initComponents();
        SchoolInfo();
        SetTrades();
        Centralize();

        // GenerateLU();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        learnUnitData = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        cmd_save = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txt_unit = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        mod = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        learningUnit = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        trd = new javax.swing.JComboBox<>();
        Genderr1 = new javax.swing.JLabel();
        lvl = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        tradeCombo = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        levels = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        luId = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_emp = new javax.swing.JLabel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        lbl_img = new javax.swing.JLabel();
        schoolName = new javax.swing.JLabel();
        about = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LEARNING UNITS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Adobe Arabic", 1, 28))); // NOI18N

        learnUnitData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        learnUnitData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                learnUnitDataMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                learnUnitDataMouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(learnUnitData);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        cmd_save.setIcon(new javax.swing.ImageIcon("C:\\Users\\ThinkPad\\Documents\\NetBeansProjects\\RPEMS\\images\\Save-icon.png")); // NOI18N
        cmd_save.setText("Save");
        cmd_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_saveActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ThinkPad\\Documents\\NetBeansProjects\\RPEMS\\images\\update icon.png")); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ThinkPad\\Documents\\NetBeansProjects\\RPEMS\\images\\delete_16x16.gif")); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ThinkPad\\Documents\\NetBeansProjects\\RPEMS\\images\\erase-128.png")); // NOI18N
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("    OPERATIONS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(cmd_save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmd_save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(15, 15, 15)
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        txt_unit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_unit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_unitActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Unit Name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Module");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("ADD LEARNING UNITS");

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        mod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Module" }));
        mod.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                modPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Learning Unit");

        learningUnit.setEditable(false);
        learningUnit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        learningUnit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                learningUnitMouseClicked(evt);
            }
        });
        learningUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                learningUnitActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("Trade");

        trd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Trade" }));
        trd.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                trdPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        trd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trdActionPerformed(evt);
            }
        });

        Genderr1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Genderr1.setText("Level:");

        lvl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Level" }));
        lvl.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                lvlPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        lvl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lvlActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Trade");

        tradeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        tradeCombo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                tradeComboPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        tradeCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tradeComboMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tradeComboMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tradeComboMouseReleased(evt);
            }
        });
        tradeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tradeComboActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Level");

        levels.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                levelsPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jButton6.setText("Search");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("L.U Indicator");

        luId.setEditable(false);
        luId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        luId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                luIdMouseClicked(evt);
            }
        });
        luId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Genderr1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(mod, javax.swing.GroupLayout.Alignment.LEADING, 0, 150, Short.MAX_VALUE)
                            .addComponent(lvl, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(trd, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(learningUnit)
                            .addComponent(txt_unit)
                            .addComponent(luId))
                        .addGap(10, 10, 10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(25, 25, 25)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(levels, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tradeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton6)
                                .addContainerGap())))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tradeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(levels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabel17)
                .addGap(157, 157, 157))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator3))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(luId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(trd, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Genderr1)
                            .addComponent(lvl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(learningUnit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_unit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)))
                .addGap(150, 150, 150))
        );

        jPanel2.setBackground(new java.awt.Color(55, 60, 68));
        jPanel2.setForeground(java.awt.Color.darkGray);
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 182, 320, 0));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\ThinkPad\\Documents\\NetBeansProjects\\RPEMS\\images\\cover_photo.png")); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 430, 180));

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\ThinkPad\\Documents\\NetBeansProjects\\RPEMS\\images\\bgg1.jpg")); // NOI18N
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 200, 170));

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\ThinkPad\\Documents\\NetBeansProjects\\RPEMS\\images\\search_20px_1.png")); // NOI18N
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));
        jPanel2.add(txt_emp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jDesktopPane2.setLayer(lbl_img, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_img, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_img, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jDesktopPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 200, 150));

        schoolName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        schoolName.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(schoolName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, 30));

        about.setBackground(new java.awt.Color(55, 60, 68));
        about.setForeground(new java.awt.Color(255, 255, 255));
        about.setIcon(new javax.swing.ImageIcon("C:\\Users\\ThinkPad\\Documents\\NetBeansProjects\\RPEMS\\images\\about.png")); // NOI18N
        about.setText("About us");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        jPanel2.add(about, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 100, 30));

        jMenu2.setText("Options");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem5.setIcon(new javax.swing.ImageIcon("C:\\Users\\ThinkPad\\Documents\\NetBeansProjects\\RPEMS\\images\\about.png")); // NOI18N
        jMenuItem5.setText("About Us");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ThinkPad\\Documents\\NetBeansProjects\\RPEMS\\images\\delete_16x16.gif")); // NOI18N
        jMenuItem3.setText("Close Window");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 346, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_unitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_unitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_unitActionPerformed
    int trdId, levId;
    String moduleId;
    private void cmd_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_saveActionPerformed
        String trad = (String) trd.getSelectedItem();
        String levl = (String) lvl.getSelectedItem();
        String module = (String) mod.getSelectedItem();
        String unit = txt_unit.getText();
        String luNum = learningUnit.getText();

        if (unit.isEmpty() || trad.equals("Select Trade") || levl.equals("Select Level") || unit.isEmpty() || luNum.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Fill all Required", "BR Software Resolution", 0);
        } else {

            int confirm = JOptionPane.showConfirmDialog(null, "You have Prepared \n " + luNum + ":" + unit + " \n to be Saved in " + module + " Module of " + trad, "BR Confirmation", JOptionPane.YES_NO_OPTION);
            if (confirm == 0) {
                String que1 = "SELECT TRADEID FROM TRADE WHERE TRADENAME=?";
                String que2 = "SELECT LEVELID FROM LEVELS WHERE LEVEL=?";
                String que3 = "SELECT MCODE FROM MODULES WHERE ModuleName=?";
                String masterQuery = "INSERT INTO LearningUnits (TRADEID,LEVELID,MCODE,Unit,LU_NAME)VALUES(?,?,?,?,?)";

                try {
                    pst = conn.prepareStatement(que1);
                    pst.setString(1, trad);
                    rs = pst.executeQuery();
                    if (rs.next()) {
                        trdId = rs.getInt("TRADEID");
                    }

                    pst = conn.prepareStatement(que2);
                    pst.setString(1, levl);
                    rs = pst.executeQuery();
                    if (rs.next()) {
                        levId = rs.getInt("LEVELID");
                    }

                    pst = conn.prepareStatement(que3);
                    pst.setString(1, module);
                    rs = pst.executeQuery();
                    if (rs.next()) {
                       moduleId = rs.getString("MCODE");
                    }

                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                } finally {
                    try {
                        pst = conn.prepareStatement(masterQuery);
                        pst.setInt(1, trdId);
                        pst.setInt(2, levId);
                        pst.setString(3, moduleId);
                        pst.setString(4, luNum);
                        pst.setString(5, unit);

                        int exec = pst.executeUpdate();
                        if (exec > 0) {
                            JOptionPane.showMessageDialog(null, "Saved", "BR Soft..",1);
                            checkForSummativeLU();
                            ClearFields();
                        }

                    } catch (SQLException e) {
                        System.out.println(e.getMessage());
                    } finally {

                    }

                }
            }

        }

    }//GEN-LAST:event_cmd_saveActionPerformed
    private void checkForSummativeLU() {
        String integratedUnit = "Summative";
        String checkQuery = "SELECT * FROM LearningUnits where MCODE=? AND Unit=?";
        String inserterQuery = "INSERT INTO LearningUnits (TRADEID,LEVELID,MCODE,Unit,LU_NAME)VALUES(?,?,?,?,?)";
        try {
            pst = conn.prepareStatement(checkQuery);
            pst.setString(1, moduleId);
            pst.setString(2, integratedUnit);
            rs = pst.executeQuery();
            if (!rs.next()) {
                try {
                    pst = conn.prepareStatement(inserterQuery);
                        pst.setInt(1, trdId);
                        pst.setInt(2, levId);
                        pst.setString(3, moduleId);
                        pst.setString(4, integratedUnit);
                        pst.setString(5, "integrated Assessment");
                        int exec = pst.executeUpdate();
                } catch (SQLException e) {
                   JOptionPane.showMessageDialog(null,e);
                }
            } else {
                
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    int realId;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String cloneId = luId.getText();
        realId = Integer.parseInt(cloneId);
        String trad = (String) trd.getSelectedItem();
        String levl = (String) lvl.getSelectedItem();
        String module = (String) mod.getSelectedItem();
        String unit = txt_unit.getText();
        String luNum = learningUnit.getText();

        if (unit.isEmpty() || trad.equals("Select Trade") || levl.equals("Select Level") || unit.isEmpty() || luNum.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Fill all Required", "BR Software Resolution", 0);
        } else {

            int confirm = JOptionPane.showConfirmDialog(null, "You have Attempted that \n " + luNum + ":" + unit + " \n to be Committed on changes in " + module + " Module of " + trad, "BR Confirmation", JOptionPane.YES_NO_OPTION);
            if (confirm == 0) {
                String que1 = "SELECT TRADEID FROM TRADE WHERE TRADENAME=?";
                String que2 = "SELECT LEVELID FROM LEVELS WHERE LEVEL=?";
                String que3 = "SELECT MCODE FROM MODULES WHERE ModuleName=?";
                String masterQuery = "UPDATE LearningUnits set TRADEID=?,LEVELID=?,MCODE=?,Unit=?,LU_NAME=? WHERE LUID=?";

                try {
                    pst = conn.prepareStatement(que1);
                    pst.setString(1, trad);
                    rs = pst.executeQuery();
                    if (rs.next()) {
                        trdId = rs.getInt("TRADEID");
                    }

                    pst = conn.prepareStatement(que2);
                    pst.setString(1, levl);
                    rs = pst.executeQuery();
                    if (rs.next()) {
                        levId = rs.getInt("LEVELID");
                    }

                    pst = conn.prepareStatement(que3);
                    pst.setString(1, module);
                    rs = pst.executeQuery();
                    if (rs.next()) {
                        moduleId = rs.getString("MCODE");
                    }

                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                } finally {
                    try {
                        pst = conn.prepareStatement(masterQuery);
                        pst.setInt(1, trdId);
                        pst.setInt(2, levId);
                        pst.setString(3, moduleId);
                        pst.setString(4, luNum);
                        pst.setString(5, unit);
                        pst.setInt(6, realId);

                        int exec = pst.executeUpdate();
                        if (exec > 0) {
                            JOptionPane.showMessageDialog(null, "Updated", "BR Soft..", JOptionPane.PLAIN_MESSAGE);
                            ClearFields();
                        }
                    } catch (SQLException e) {
                        System.out.println(e.getMessage());
                    }

                }
            }

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String cloneId = luId.getText();
        realId = Integer.parseInt(cloneId);
        String trad = (String) trd.getSelectedItem();
        String levl = (String) lvl.getSelectedItem();
        String module = (String) mod.getSelectedItem();
        String unit = txt_unit.getText();
        String luNum = learningUnit.getText();
        if (unit.isEmpty() || trad.equals("Select Trade") || levl.equals("Select Level") || unit.isEmpty() || luNum.isEmpty()) {
            JOptionPane.showMessageDialog(null, "You Can Delete with Modified Fields", "BR Software Resolution", 0);
        } else {
            int Confirm = JOptionPane.showConfirmDialog(null, "Are You Sure You want to Delete", "BR Software Resolution", JOptionPane.YES_NO_OPTION);
            if (Confirm == 0) {

                try {

                    String updator = "DELETE FROM LearningUnits WHERE LUID=?";

                    pst = conn.prepareStatement(updator);

                    pst.setInt(1, realId);

                    int runnable = pst.executeUpdate();
                    if (runnable > 0) {
                        JOptionPane.showMessageDialog(null, "Deleted Successfully", "BR Software Resolution", 1);
                        ClearFields();
                        learnUnitData.clearSelection();
                        //ListSelectionModel selectedProduct = learnUnitData.getSelectionModel();

                    }

                } catch (SQLException e) {
                    System.out.print(e.getMessage());
                }

            }

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ClearFields();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        //        // TODO add your handling code here:
        //        int x = evt.getXOnScreen();
        //        int y = evt.getYOnScreen();
        //        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        //        // TODO add your handling code here:
        //        xx = evt.getX();
        //        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void learnUnitDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_learnUnitDataMouseClicked

        int[] StudentRow = learnUnitData.getSelectedRows();
        int row = StudentRow[0];
        Object identity = learnUnitData.getValueAt(row, 0);
        String id = String.valueOf(identity);
        int value = Integer.parseInt(id);
        Search(value);
        cmd_save.setEnabled(false);


    }//GEN-LAST:event_learnUnitDataMouseClicked

    private void learnUnitDataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_learnUnitDataMouseExited
        // cmd_save.setVisible(false);
    }//GEN-LAST:event_learnUnitDataMouseExited

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        new About_Us().setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        new About_Us().setVisible(true);
    }//GEN-LAST:event_aboutActionPerformed

    private void learningUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_learningUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_learningUnitActionPerformed

    private void trdPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_trdPopupMenuWillBecomeInvisible
        lvl.removeAllItems();
        lvl.addItem("Select Level");
        PopUp();
    }//GEN-LAST:event_trdPopupMenuWillBecomeInvisible

    private void lvlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lvlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lvlActionPerformed

    private void trdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trdActionPerformed

    private void tradeComboPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_tradeComboPopupMenuWillBecomeInvisible

        levels.removeAllItems();
        PopUp2();
    }//GEN-LAST:event_tradeComboPopupMenuWillBecomeInvisible

    private void tradeComboMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tradeComboMouseExited

    }//GEN-LAST:event_tradeComboMouseExited

    private void tradeComboMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tradeComboMousePressed
        // SetTrades();
    }//GEN-LAST:event_tradeComboMousePressed

    private void tradeComboMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tradeComboMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tradeComboMouseReleased

    private void tradeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tradeComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tradeComboActionPerformed

    private void levelsPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_levelsPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_levelsPopupMenuWillBecomeInvisible

    private void luIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luIdActionPerformed
        JOptionPane.showMessageDialog(null, "ID IS AUTO-GENERATED", "BR Warning", JOptionPane.WARNING_MESSAGE);

    }//GEN-LAST:event_luIdActionPerformed

    private void luIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_luIdMouseClicked
        JOptionPane.showMessageDialog(null, "ID IS AUTO-GENERATED", "BR Warning", JOptionPane.WARNING_MESSAGE);

    }//GEN-LAST:event_luIdMouseClicked

    private void lvlPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_lvlPopupMenuWillBecomeInvisible
        mod.removeAllItems();
        mod.addItem("Select Module");
        moduleShow();
    }//GEN-LAST:event_lvlPopupMenuWillBecomeInvisible

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        LookUp();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void learningUnitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_learningUnitMouseClicked
        JOptionPane.showMessageDialog(null, "Unit already set for you", "BR Warning", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_learningUnitMouseClicked

    private void modPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_modPopupMenuWillBecomeInvisible
        learningUnit.setText("");
        GenerateLU();
    }//GEN-LAST:event_modPopupMenuWillBecomeInvisible

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LUnits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LUnits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LUnits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LUnits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LUnits().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Genderr1;
    private javax.swing.JButton about;
    private javax.swing.JButton cmd_save;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lbl_img;
    private javax.swing.JTable learnUnitData;
    private javax.swing.JTextField learningUnit;
    private javax.swing.JComboBox<String> levels;
    private javax.swing.JTextField luId;
    private javax.swing.JComboBox<String> lvl;
    private javax.swing.JComboBox<String> mod;
    private javax.swing.JLabel schoolName;
    private javax.swing.JComboBox<String> tradeCombo;
    private javax.swing.JComboBox<String> trd;
    private javax.swing.JLabel txt_emp;
    private javax.swing.JTextField txt_unit;
    // End of variables declaration//GEN-END:variables

    private void Search(int id) {

        String sql = "SELECT LUID,TRADE.TRADENAME,levels.LEVEL,modules.ModuleName,Unit,LU_NAME FROM learningunits JOIN trade USING(TRADEID) JOIN levels USING(LEVELID)JOIN modules USING(MCODE) WHERE LUID=?";
        try {
            pst = conn.prepareStatement(sql);
            pst.setInt(1, id);
            rs = pst.executeQuery();
            if (rs.next()) {
                int modId = rs.getInt("LUID");
                luId.setText(String.valueOf(modId));

                String trade = rs.getString("TRADENAME");
                trd.removeAllItems();
                trd.addItem(trade);

                String level = rs.getString("LEVEL");
                lvl.removeAllItems();
                lvl.addItem(level);

                String module = rs.getString("ModuleName");
                mod.removeAllItems();
                mod.addItem("Select Module");
                mod.addItem(module);
                mod.setSelectedItem(module);

                String unit = rs.getString("UNIT");
                learningUnit.setText(unit);

                String unitName = rs.getString("LU_NAME");
                txt_unit.setText(unitName);
            }

            //byte[] img = rs.getBytes("Image");
            //imageIcon imageIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(lbl_img.getWidth(), lbl_img.getHeight(), Image.SCALE_SMOOTH));
            //lbl_img.setIcon(imageIcon);
        } catch (SQLException e) {
            System.out.print("Caught : " + e);
        }
    }

    private void ClearFields() {
        luId.setText("");
        tradeCombo.removeAllItems();
        trd.removeAllItems();
        tradeCombo.addItem("Select");
        trd.addItem("Select Trade");
        SetTrades();
        levels.removeAllItems();
        lvl.removeAllItems();
        lvl.addItem("Select Level");
        learningUnit.setText("");
        txt_unit.setText("");
        cmd_save.setEnabled(true);
        learnUnitData.clearSelection();
        learnUnitData.createDefaultColumnsFromModel();

    }

    private void SchoolInfo() {
        try {
            pst = conn.prepareStatement("SELECT * FROM SCHOOL_INFO");
            rs = pst.executeQuery();
            if (rs.next()) {
                schoolName.setText(rs.getString("SchoolName"));
                Blob filenameBlob = rs.getBlob("Logo");
                byte[] content = filenameBlob.getBytes(1L, (int) filenameBlob.length());
                ImageIcon ik = new ImageIcon(content);
                Image img = ik.getImage();
                //ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(lbl_img.getWidth(), lbl_img.getHeight(), Image.SCALE_DEFAULT));
                Image newimg = img.getScaledInstance(lbl_img.getWidth(), lbl_img.getHeight(), Image.SCALE_DEFAULT);
                ik = new ImageIcon(newimg);
                lbl_img.setIcon(ik);
            }
        } catch (SQLException e) {
        }

    }
    int realValue;

    private void PopUp() {

        String tmp = (String) trd.getSelectedItem();
        if (tmp.equals("Select Trade")) {
            lvl.removeAllItems();
            lvl.addItem("Select Level");

        }
        String sql = "SELECT TRADEID FROM TRADE WHERE TRADENAME=?";
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, tmp);
            rs = pst.executeQuery();
            if (rs.next()) {
                realValue = rs.getInt("TRADEID");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                String sql2 = "SELECT * FROM LEVELS WHERE TRADEID=?";
                pst = conn.prepareStatement(sql2);
                pst.setInt(1, realValue);
                rs = pst.executeQuery();

                while (rs.next()) {

                    String add1 = rs.getString("LEVEL");
                    lvl.addItem(add1);

                }

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }

        }
    }

    private void SetTrades() {
        try {
            String query = "SELECT * FROM TRADE";
            pst = conn.prepareStatement(query);
            rs = pst.executeQuery();

            while (rs.next()) {
                String data = rs.getString("TRADENAME");
                trd.addItem(data);
                tradeCombo.addItem(data);

            }

        } catch (SQLException ex) {
            System.out.print(ex.getMessage());
        }
    }

    private void PopUp2() {
        String tmp = (String) tradeCombo.getSelectedItem();
        String sql = "SELECT TRADEID FROM TRADE WHERE TRADENAME=?";
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, tmp);
            rs = pst.executeQuery();
            if (rs.next()) {
                realValue = rs.getInt("TRADEID");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                String sql2 = "SELECT * FROM LEVELS WHERE TRADEID=?";
                pst = conn.prepareStatement(sql2);
                pst.setInt(1, realValue);
                rs = pst.executeQuery();

                while (rs.next()) {

                    String add1 = rs.getString("LEVEL");

                    levels.addItem(add1);

                }

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }

    int realVal2;

    private void moduleShow() {
        String temp = (String) trd.getSelectedItem();
        String tmp = (String) lvl.getSelectedItem();
        if (temp.equals("Select Trade") || tmp.equals("Select Level")) {
            mod.removeAllItems();
            mod.addItem("Select Module");
        } else {
            String sql = "SELECT LEVELID FROM LEVELS WHERE LEVEL=?";
            String sqln2 = "SELECT TRADEID FROM TRADE WHERE TRADENAME=?";
            try {
                pst = conn.prepareStatement(sql);

                pst.setString(1, tmp);
                rs = pst.executeQuery();
                if (rs.next()) {
                    realValue = rs.getInt("LEVELID");
                }
                pst = conn.prepareStatement(sqln2);
                pst.setString(1, temp);
                rs = pst.executeQuery();
                if (rs.next()) {
                    realVal2 = rs.getInt("TRADEID");
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            } finally {
                try {
                    String sql2 = "SELECT * FROM MODULES WHERE LEVELID=? and TRADEID=?";
                    pst = conn.prepareStatement(sql2);
                    pst.setInt(1, realValue);
                    pst.setInt(2, realVal2);
                    rs = pst.executeQuery();

                    while (rs.next()) {

                        String add1 = rs.getString("MODULENAME");
                        mod.addItem(add1);

                    }

                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        }

    }

    public void LookUp() {
        String trad = (String) tradeCombo.getSelectedItem();
        String levl = (String) levels.getSelectedItem();

        String query = "SELECT LUID,TRADE.TRADENAME,levels.LEVEL,modules.ModuleName,Unit,LU_NAME FROM learningunits JOIN trade USING(TRADEID) JOIN levels USING(LEVELID)JOIN modules USING(MCODE) WHERE TRADENAME=? AND LEVEL=? and LU_NAME!='Summative' LIMIT 100";
        try {
            //  String[] cols = {"REGNO", "TRADENAME"};
            pst = conn.prepareStatement(query);
            pst.setString(1, trad);
            pst.setString(2, levl);
            rs = pst.executeQuery();

            learnUnitData.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }

    }
    String regvalue;
    int res;

    public String GenerateLU() {
        String trad = (String) trd.getSelectedItem();
        String levl = (String) lvl.getSelectedItem();
        String module = (String) mod.getSelectedItem();
        if (trad.equals("Select Trade") || levl.equals("Select Level") || module.equals("Select Module")) {
            learningUnit.setText("");
        } else {
            try {
                String sql = "SELECT COUNT(LUID) AS NUMBERS,TRADE.TRADENAME,levels.LEVEL,modules.ModuleName,Unit,LU_NAME FROM learningunits JOIN trade USING(TRADEID) JOIN levels USING(LEVELID)JOIN modules USING(MCODE) WHERE TRADENAME=? AND LEVEL=? AND ModuleName=? AND Unit!='Summative'";
                pst = conn.prepareStatement(sql);
                pst.setString(1, trad);
                pst.setString(2, levl);
                pst.setString(3, module);
                rs = pst.executeQuery();
                if (rs.next()) {
                    res = (rs.getInt("NUMBERS"));
                }

                int regno = res + 1;
           if(regno>1 & regno<2){
                regno = regno - 1;
           }
                regvalue = "Learning Unit " + String.valueOf(regno);
                learningUnit.setText(regvalue);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "ErOR" + e);
            }

        }

        return regvalue;
    }

    private void Centralize() {
        WindowSetter.sizeWindow(this);
    }

}
