/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edubit;

import Test.*;
import edubit.*;
import java.awt.HeadlessException;
import java.awt.Image;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author ThinkPad
 */
public final class Trades extends javax.swing.JFrame {

    Connection conn = db.java_db();
    ;
    ResultSet rs = null;
    PreparedStatement pst = null;
    int result;

//    public int GenerateRegno() {
//        try {
//            String sql = "select Count(TRADEID) as Numbers from TRADE";
//            pst = conn.prepareStatement(sql);
//            rs = pst.executeQuery();
//
//            if (rs.next()) {
//                result = (rs.getInt(1));
//            }
//        } catch (SQLException e) {
//        }
//
//        int regno = result + 1;
//        int regvalue = regno;
//        tradeNo.setText(String.valueOf(regvalue));
//        return regvalue;
//    }
    private void Update_table() {
        try {
            String sql = "select TRADE.TRADEID,SECTORS.SECNAME as SECTOR ,TRADENAME FROM TRADE JOIN SECTORS USING(SECID) LIMIT 20";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            tradestbl.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error HERE : " + e);
        }
    }

    /**
     * Creates new form Home_Data
     */
    /**
     * Creates new form Sectors
     */
    public Trades() {
        initComponents();
        SchoolInfo();
        Update_table();
        SetSectors();
        loader.setVisible(false);
        Centralize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        lbl_img = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tradestbl = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        cmd_save = new javax.swing.JButton();
        upt = new javax.swing.JButton();
        del = new javax.swing.JButton();
        clr = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        loader = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        tradelbl = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tradeNo = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        choice1 = new java.awt.Choice();
        jLabel13 = new javax.swing.JLabel();
        sector = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        tradeName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_emp = new javax.swing.JLabel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        lblimg = new javax.swing.JLabel();
        schoolName = new javax.swing.JLabel();
        about = new javax.swing.JButton();

        jDesktopPane1.setLayer(lbl_img, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_img, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_img, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TRADES IN DEPARTMENTS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Adobe Arabic", 1, 28))); // NOI18N

        tradestbl.setAutoCreateRowSorter(true);
        tradestbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tradestbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tradestblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tradestbl);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        cmd_save.setIcon(new javax.swing.ImageIcon("C:\\Users\\ThinkPad\\Documents\\NetBeansProjects\\RPEMS\\images\\Save-icon.png")); // NOI18N
        cmd_save.setText("Save");
        cmd_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_saveActionPerformed(evt);
            }
        });

        upt.setIcon(new javax.swing.ImageIcon("C:\\Users\\ThinkPad\\Documents\\NetBeansProjects\\RPEMS\\images\\update icon.png")); // NOI18N
        upt.setText("Update");
        upt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uptActionPerformed(evt);
            }
        });

        del.setIcon(new javax.swing.ImageIcon("C:\\Users\\ThinkPad\\Documents\\NetBeansProjects\\RPEMS\\images\\delete_16x16.gif")); // NOI18N
        del.setText("Delete");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });

        clr.setIcon(new javax.swing.ImageIcon("C:\\Users\\ThinkPad\\Documents\\NetBeansProjects\\RPEMS\\images\\erase-128.png")); // NOI18N
        clr.setText("Clear");
        clr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("CRUD OPERATIONS");

        loader.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        loader.setIcon(new javax.swing.ImageIcon("C:\\Users\\ThinkPad\\Documents\\NetBeansProjects\\RPEMS\\images\\waitloader.gif")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmd_save, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(upt)
                    .addComponent(del)
                    .addComponent(clr, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loader, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmd_save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(upt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(del, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clr)
                .addGap(15, 15, 15)
                .addComponent(loader)
                .addGap(18, 18, 18))
        );

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Sector");

        tradelbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tradelbl.setText("TradeNo");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("ADD NEW DEPARTMENT TRADE");

        tradeNo.setEditable(false);
        tradeNo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tradeNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tradeNoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tradeNoMousePressed(evt);
            }
        });

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("TRADES");

        choice1.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Sub-Sectors");

        sector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Sector" }));
        sector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sectorActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("TradeName");

        jButton1.setText("Search");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tradelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tradeNo)
                            .addComponent(sector, 0, 176, Short.MAX_VALUE)
                            .addComponent(tradeName)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jSeparator3)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(tradelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tradeNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sector, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tradeName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(61, 61, 61))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton1)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel10))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)
                                .addGap(7, 7, 7))
                            .addComponent(jSeparator4))
                        .addGap(150, 150, 150))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jPanel2.setBackground(new java.awt.Color(55, 60, 68));
        jPanel2.setForeground(java.awt.Color.darkGray);
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 182, 320, 0));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\ThinkPad\\Documents\\NetBeansProjects\\RPEMS\\images\\Copy of cover_photo.png")); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 370, 160));

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\ThinkPad\\Documents\\NetBeansProjects\\RPEMS\\images\\ssss\\rptech.png")); // NOI18N
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 200, 120));
        jPanel2.add(txt_emp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jDesktopPane2.setLayer(lblimg, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblimg, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblimg, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jDesktopPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 180, 140));

        schoolName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        schoolName.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(schoolName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, 30));

        about.setBackground(new java.awt.Color(204, 204, 0));
        about.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        about.setIcon(new javax.swing.ImageIcon("C:\\Users\\ThinkPad\\Documents\\NetBeansProjects\\RPEMS\\images\\closer.png")); // NOI18N
        about.setText("Close");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        jPanel2.add(about, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 306, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
int realValue;
    private void cmd_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_saveActionPerformed
        String trade = tradeNo.getText();
        String sectref = (String) sector.getSelectedItem();
        String tradename = tradeName.getText();
        if (tradename.isEmpty() || sectref.equals("Select Sector")) {
            JOptionPane.showMessageDialog(null, "Fill Fields", "BR Software Resolution", 0);
            ClearFields();
        } else {
            int confirm = JOptionPane.showConfirmDialog(null, "Sure?", "BR Software Resolution", JOptionPane.YES_NO_OPTION);
            if (confirm == 0) {
                SwingWorker<Void, String> mySwingWorker;
                mySwingWorker = new SwingWorker<Void, String>() {
                    @Override
                    public Void doInBackground() throws InterruptedException {

                        SaveTrade();
                        Thread.sleep(500);
                        return null;
                    }
                };
                JButton btns[] = {upt, del, clr};
                String waitMsg = "Loading...";
                PleaseWait x = new PleaseWait();
                x.geekExecute(evt, mySwingWorker, loader, waitMsg, btns);

            }

        }


    }//GEN-LAST:event_cmd_saveActionPerformed

    private void uptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uptActionPerformed
        String trade = tradeNo.getText();
        String sectref = (String) sector.getSelectedItem();
        String tradename = tradeName.getText();
        if (trade.isEmpty() || tradename.isEmpty() || sectref.equals("Select Sector")) {
            JOptionPane.showMessageDialog(null, "No Selected Sector to Update", "BR Software Resolution", 0);
            ClearFields();
        } else {
            int Confirm = JOptionPane.showConfirmDialog(null, "Are You Sure You want to Commit Changes", "BR Software Resolution", JOptionPane.YES_NO_OPTION);
            if (Confirm == 0) {
                SwingWorker<Void, String> mySwingWorker;
                mySwingWorker = new SwingWorker<Void, String>() {
                    @Override
                    public Void doInBackground() throws InterruptedException {
                        UpdateAction();
                        Thread.sleep(500);
                        return null;
                    }
                };
                JButton btns[] = {};
                String waitMsg = "Loading...";
                PleaseWait x = new PleaseWait();
                x.geekExecute(evt, mySwingWorker, loader, waitMsg, btns);
            }

        }
    }//GEN-LAST:event_uptActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        String trade = tradeNo.getText();
        String sectref = (String) sector.getSelectedItem();
        String tradename = tradeName.getText();
        if (trade.isEmpty() || tradename.isEmpty() || sectref.equals("Select Sector")) {
            JOptionPane.showMessageDialog(null, "No selected Sector to delete", "BR Software Resolution", 0);
            ClearFields();
        } else {
            int Confirm = JOptionPane.showConfirmDialog(null, "Are You Sure You want to Delete", "BR Software Resolution", JOptionPane.YES_NO_OPTION);
            if (Confirm == 0) {
                SwingWorker<Void, String> mySwingWorker;
                mySwingWorker = new SwingWorker<Void, String>() {
                    @Override
                    public Void doInBackground() throws InterruptedException {
                        DelAction();
                        Thread.sleep(500);
                        return null;
                    }
                };
                JButton btns[] = {};
                String waitMsg = "Loading...";
                PleaseWait x = new PleaseWait();
                x.geekExecute(evt, mySwingWorker, loader, waitMsg, btns);
            }

        }


    }//GEN-LAST:event_delActionPerformed

    private void clrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrActionPerformed
        ClearFields();
    }//GEN-LAST:event_clrActionPerformed

    private void tradestblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tradestblMouseClicked
        cmd_save.setEnabled(false);
        int[] StudentRow = tradestbl.getSelectedRows();
        int row = StudentRow[0];
        Object identity = tradestbl.getValueAt(row, 0);
        String id = String.valueOf(identity);
        int value = Integer.parseInt(id);
        Search(value);

    }//GEN-LAST:event_tradestblMouseClicked

    private void sectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sectorActionPerformed

    }//GEN-LAST:event_sectorActionPerformed

    private void tradeNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tradeNoMouseClicked
        JOptionPane.showMessageDialog(null, "ID IS AUTO-GENERATED", "BR Warning", JOptionPane.WARNING_MESSAGE);

    }//GEN-LAST:event_tradeNoMouseClicked

    private void tradeNoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tradeNoMousePressed
        JOptionPane.showMessageDialog(null, "ID IS AUTO-GENERATED", "BR Warning", JOptionPane.WARNING_MESSAGE);

    }//GEN-LAST:event_tradeNoMousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        //        // TODO add your handling code here:
        //        int x = evt.getXOnScreen();
        //        int y = evt.getYOnScreen();
        //        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        //        // TODO add your handling code here:
        //        xx = evt.getX();
        //        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        this.dispose();
    }//GEN-LAST:event_aboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton about;
    private java.awt.Choice choice1;
    private javax.swing.JButton clr;
    private javax.swing.JButton cmd_save;
    private javax.swing.JButton del;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lbl_img;
    private javax.swing.JLabel lblimg;
    private javax.swing.JLabel loader;
    private javax.swing.JLabel schoolName;
    private javax.swing.JComboBox<String> sector;
    private javax.swing.JTextField tradeName;
    private javax.swing.JTextField tradeNo;
    private javax.swing.JLabel tradelbl;
    private javax.swing.JTable tradestbl;
    private javax.swing.JLabel txt_emp;
    private javax.swing.JButton upt;
    // End of variables declaration//GEN-END:variables

    private void ClearFields() {
        cmd_save.setEnabled(true);
        tradeNo.setText("");
        sector.setSelectedIndex(0);
        tradeName.setText("");
        tradestbl.clearSelection();
    }

    private void SetSectors() {
        try {
            String query = "SELECT * FROM SECTORS";
            Statement st = conn.createStatement();
            rs = st.executeQuery(query);

            while (rs.next()) {
                String data = rs.getString("SECNAME");
                sector.addItem(data);
            }

        } catch (SQLException ex) {
            System.out.print(ex.getMessage());
        }
    }

    private void Search(int id) {

        String sql = "select * from TRADE where TRADEID=?";
        try {
            pst = conn.prepareStatement(sql);
            pst.setInt(1, id);
            rs = pst.executeQuery();
            if (rs.next()) {
                int add1 = rs.getInt("TRADEID");
                tradeNo.setText(String.valueOf(add1));

                String add3 = rs.getString("TRADENAME");
                tradeName.setText(add3);
                pst = conn.prepareStatement("Select SECTORS.SECNAME as SECTORS from TRADE JOIN SECTORS USING(SECID) where SECID=" + rs.getInt("SECID"));
                rs = pst.executeQuery();
                if (rs.next()) {
                    String add2 = rs.getString("SECTORS");
                    sector.setSelectedItem(add2);
                }
            }

            //byte[] img = rs.getBytes("Image");
            //imageIcon imageIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(lbl_img.getWidth(), lbl_img.getHeight(), Image.SCALE_SMOOTH));
            //lbl_img.setIcon(imageIcon);
        } catch (SQLException e) {
            System.out.print("Caught : " + e);
        }
    }

    private void SchoolInfo() {
        try {
            pst = conn.prepareStatement("SELECT * FROM SCHOOL_INFO");
            rs = pst.executeQuery();
            if (rs.next()) {
                schoolName.setText(rs.getString("SchoolName"));
                Blob filenameBlob = rs.getBlob("Logo");
                byte[] content = filenameBlob.getBytes(1L, (int) filenameBlob.length());
                ImageIcon ik = new ImageIcon(content);
                Image img = ik.getImage();
                //ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(lbl_img.getWidth(), lbl_img.getHeight(), Image.SCALE_DEFAULT));
                Image newimg = img.getScaledInstance(lblimg.getWidth(), lblimg.getHeight(), Image.SCALE_DEFAULT);
                ik = new ImageIcon(newimg);
                lblimg.setIcon(ik);
            }
        } catch (SQLException e) {
        }

    }

    private void SaveTrade() {
        String trade = tradeNo.getText();
        String sectref = (String) sector.getSelectedItem();
        String tradename = tradeName.getText();

        try {
            pst = conn.prepareStatement("SELECT SECID FROM SECTORS WHERE SECNAME=?");
            pst.setString(1, sectref);
            rs = pst.executeQuery();
            if (rs.next()) {
                realValue = rs.getInt("SECID");
            }
        } catch (SQLException e) {
            System.out.print(e.getMessage());
        } finally {
            try {

                pst = conn.prepareStatement("INSERT INTO TRADE(SECID,TRADENAME) VALUES(?,?)");
                pst.setInt(1, realValue);
                pst.setString(2, tradename);
                int exec = pst.executeUpdate();
                if (exec > 0) {
                    JOptionPane.showMessageDialog(null, "Trade " + tradename + " Has been Added!", "BR Software Resolution", JOptionPane.INFORMATION_MESSAGE);

                    ClearFields();
                    Update_table();

                }

            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }

    }

    private void UpdateAction() {
        String trade = tradeNo.getText();
        String sectref = (String) sector.getSelectedItem();
        String tradename = tradeName.getText();
        try {
            pst = conn.prepareStatement("SELECT SECID FROM SECTORS WHERE SECNAME=?");
            pst.setString(1, sectref);
            rs = pst.executeQuery();
            if (rs.next()) {
                realValue = rs.getInt("SECID");
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        } finally {
            try {
                pst = conn.prepareStatement("UPDATE TRADE SET SECID=?,TRADENAME=? WHERE TRADEID=?");
                pst.setInt(1, realValue);
                pst.setString(2, tradename);
                pst.setInt(3, Integer.parseInt(trade));
                int exec = pst.executeUpdate();
                if (exec == 1) {
                    JOptionPane.showMessageDialog(null, "Updated Successfully", "BR Software Resolution", 1);
                    ClearFields();
                    Update_table();
                }
            } catch (SQLException ex) {
                System.out.print(ex.getMessage());
            }

        }

    }

    private void DelAction() {
        String trade = tradeNo.getText();
        String sectref = (String) sector.getSelectedItem();
        String tradename = tradeName.getText();
        // String sector = txt_sec.getText();
        int id = Integer.parseInt(trade);
        try {
            String casc = "DELETE FROM LEVELS WHERE TRADEID=?";
            String updator = "DELETE FROM TRADE WHERE TRADEID=?";
            pst = conn.prepareStatement(casc);
            pst.setInt(1, id);
            pst.execute();
            pst = conn.prepareStatement(updator);

            pst.setInt(1, id);

            int runnable = pst.executeUpdate();
            if (runnable > 0) {
                JOptionPane.showMessageDialog(null, "Deleted Successfully", "BR Software Resolution", 1);
                ClearFields();
                Update_table();

            }

        } catch (SQLException e) {
            System.out.print(e.getMessage());
        }

    }

    private void Centralize() {
        WindowSetter.sizeWindow(this);
    }

}
